Задание 1-1 Программа
crocodile09111698/Programmimg-C pull request #3
Opened 2021-04-08 12:11 UTC by crocodile09111698

1. Создание программы
2. Добавление данных своего варианта(6)

2021-04-08 12:15 UTC, crocodile09111698 commented
[Задание 1-1 результат.docx](https://github.com/crocodile09111698/Programmimg-C/files/6278514/1-1.docx)

Результат программы. Я просто не уверена что она там отобразился, хотя я его коммитила

2021-04-14 15:26 UTC, MarinaPaley requested changes
и не забыть документацию

2021-04-14 15:26 UTC, MarinaPaley commented on main.cpp
> +    const auto a = pow(x,3) * pow(tan(x+y),2) + z/sqrt(x+y);
Все ок, только нужно этот рачет поместить в отдельную функцию ( как на лекции)

2021-04-14 15:28 UTC, merged

2021-04-14 17:21 UTC, MarinaPaley commented
НЕ БЫЛО approve!