1-2
crocodile09111698/Programmimg-C pull request #4
Opened 2021-04-08 13:24 UTC by crocodile09111698

Задание 1-2. Вариант 6. Найти расстояние между двумя точками с заданными координатами

2021-04-08 13:25 UTC, crocodile09111698 commented
Я запуталась немного в ветках, наверно поэтому так много коммитов приложилось.  Вам нужны последние(нижние) 2 файла.

2021-04-14 15:28 UTC, merged

2021-04-14 15:28 UTC, MarinaPaley requested changes

2021-04-14 15:28 UTC, MarinaPaley commented on Задание 1-2.cpp
> +const auto Rasstoyanie = sqrt((x2-x1)*(x2-x1)+(y2-y1)*(y2-y1));
мы не пишем транслитом - getDistance()
Вынест в отдельную функцию.
Написать документацию

2021-04-14 17:20 UTC, MarinaPaley commented
![image](https://user-images.githubusercontent.com/26978698/114752303-d15dbc80-9d5e-11eb-8730-a4b82d5522c7.png)
ГДЕ APPROVE?